name: basic-task
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: cmscloud/al9-cms:latest
    steps:
      - name: my-step
        run: |
          echo "Hello World!"
          cat /etc/os-release
      - name: my-final-step
        run: echo "Finished task"
        shell: bash
